
variables:
  VERSION: 1.0.$CI_PIPELINE_ID

  EVENT_BUS_CLIENT_BRANCH: master
  EVENT_BUS_CLIENT_VERSION: 1.0.194

stages:
  - test
  - build
  - release

before_script:
  - mkdir -p include
  - "wget -O include/eventbusclient-$EVENT_BUS_CLIENT_VERSION.jar --header \"PRIVATE-TOKEN: $SECRET_APIKEY\" \"http://sed-team-project/SED-DEV-group/event-bus-client-lib/builds/artifacts/$EVENT_BUS_CLIENT_BRANCH/raw/target/eventbusclient-$EVENT_BUS_CLIENT_VERSION.jar?job=build\""
  - jar tf include/eventbusclient-$EVENT_BUS_CLIENT_VERSION.jar

test:
  stage: test
  image: maven:3-jdk-8
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: userservice
    POSTGRES_USER: userservice
    POSTGRES_PASSWORD: userservice
  script:
    - mvn -Deventbusclient.version=$EVENT_BUS_CLIENT_VERSION test
  artifacts:
    paths:
      - target/jacoco-ut/*

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn -DskipTests -Deventbusclient.version=$EVENT_BUS_CLIENT_VERSION versions:set -DnewVersion=$VERSION
    - mvn -DskipTests -Deventbusclient.version=$EVENT_BUS_CLIENT_VERSION -D clean package
  artifacts:
    paths:
      - target/*.jar
